version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoId
      MONGO_INITDB_ROOT_PASSWORD: mongoPw
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: adminId
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminPw
      ME_CONFIG_MONGODB_URL: mongodb://mongoId:mongoPw@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: expressId
      ME_CONFIG_BASICAUTH_PASSWORD: expressPw